name: CI

on:
  push:

env:
  ARTIFACT_NAME: site
  BUILD_DIRECTORY: "./dist"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run export

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BUILD_DIRECTORY }}
          if-no-files-found: error
          retention-days: 7
